# 🧬 DNA Sequence Classification Using Machine Learning

## Introduction

DNA sequence classification is a fundamental task in bioinformatics that involves identifying the functional role of DNA sequences based on their nucleotide patterns. Accurate classification of DNA sequences plays an important role in understanding gene regulation, disease diagnosis, and various genomic research applications.

In this project, machine learning techniques are applied to classify DNA sequences using a promoter gene dataset. The workflow includes data loading, preprocessing, exploratory data analysis, feature engineering, model training, prediction, and performance evaluation.

The objective of this project is to develop a reliable classification model that can accurately predict the class of DNA sequences while demonstrating a complete end-to-end machine learning pipeline.

---

## Project Objectives

- Load and understand the DNA sequence dataset.
- Perform exploratory data analysis (EDA).
- Preprocess the dataset for machine learning.
- Convert categorical features into numerical representations.
- Split the dataset into training and testing sets.
- Train machine learning classification models.
- Evaluate model performance using appropriate metrics.
- Compare model results to identify the best-performing classifier.

---

## Technologies Used

- Python
- Jupyter Notebook
- Pandas
- NumPy
- Scikit-learn
- Matplotlib

---

## Project Workflow

1. Import required libraries.
2. Load the DNA sequence dataset.
3. Explore and understand the data.
4. Perform data preprocessing and feature encoding.
5. Split the dataset into training and testing sets.
6. Train machine learning models.
7. Make predictions on unseen data.
8. Evaluate model performance.
9. Compare model results and draw conclusions.

---

**Internship:** Data Science Bootcamp

**Organization:** IIIT Kottayam

**Project:** DNA Sequence Classification Using Machine Learning

## Step 1: Import Required Libraries and Load the Dataset

The following code cells will import necessary libraries and import the dataset from the UCI repository as a Pandas DataFrame.

In [ ]:
# Display the versions of Python and the required libraries
# to ensure compatibility and reproducibility.
import sys
import numpy
import sklearn
import pandas

print('Python: {}'.format(sys.version))
print('Numpy: {}'.format(numpy.__version__))
print('Sklearn: {}'.format(sklearn.__version__))
print('Pandas: {}'.format(pandas.__version__))

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Numpy: 2.0.2
Sklearn: 1.6.1
Pandas: 2.2.2

In [ ]:
# Import Required Libraries
# pandas      : Data manipulation and analysis
# numpy       : Numerical computations
# matplotlib  : Data visualization
# sklearn     : Machine Learning algorithms and evaluation
import numpy as np
import pandas as pd

# import the uci Molecular Biology (Promoter Gene Sequences) Data Set
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/molecular-biology/promoter-gene-sequences/promoters.data'
names = ['Class', 'id', 'Sequence']
# Load the DNA Sequence Dataset
# ==========================================================

# Read the promoter gene sequence dataset into a pandas DataFrame.
data = pd.read_csv(url, names = names)

In [ ]:
# Display the first five rows of the dataset
df.head()

,0_a,0_c,0_g,0_t,1_a,1_c,1_g,1_t,2_a,2_c,...,54_t,55_a,55_c,55_g,55_t,56_a,56_c,56_g,56_t,Class
0,False,False,False,True,True,False,False,False,False,True,...,False,False,False,True,False,False,False,False,True,True
1,False,False,False,True,False,False,True,False,False,True,...,False,True,False,False,False,True,False,False,False,True
2,False,False,True,False,False,False,False,True,True,False,...,False,False,True,False,False,False,False,True,False,True
3,True,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,True
4,False,False,False,True,False,True,False,False,False,False,...,True,True,False,False,False,False,False,True,False,True

In [ ]:
# Display the first record in the dataset to understand
# its structure and attributes.
print(data.iloc[0]);

Class                                                       +
id                                                        S10
Sequence    \t\ttactagcaatacgcttgcgttcggtggttaagtatgtataat...
Name: 0, dtype: object

## Step 2: Data Preprocessing and Feature Engineering

*   List item

The data is not in a usable form; as a result, we will need to process it before using it to train our algorithms.

In [ ]:
# ==========================================================
# Data Preprocessing
# ==========================================================
# Convert categorical variables into numerical values
# Prepare the dataset for machine learning.
# Display dataset information such as column names,
# data types, and missing values.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 106 entries, 0 to 105
Columns: 229 entries, 0_a to Class
dtypes: bool(229)
memory usage: 28.6 KB

In [ ]:
# Building our Dataset by creating a custom Pandas DataFrame
# Each column in a DataFrame is called a Series. Lets start by making a series for each column.

classes = data.loc[:, 'Class']
print(classes[:5])

0    +
1    +
2    +
3    +
4    +
Name: Class, dtype: object

In [ ]:
# generate list of DNA sequences
sequences = list(data.loc[:, 'Sequence'])
dataset = {}

# loop through sequences and split into individual nucleotides
for i, seq in enumerate(sequences):

    # split into nucleotides, remove tab characters
    nucleotides = list(seq)
    nucleotides = [x for x in nucleotides if x != '\t']

    # append class assignment
    nucleotides.append(classes[i])

    # add to dataset
    dataset[i] = nucleotides

print(dataset[0])

['t', 'a', 'c', 't', 'a', 'g', 'c', 'a', 'a', 't', 'a', 'c', 'g', 'c', 't', 't', 'g', 'c', 'g', 't', 't', 'c', 'g', 'g', 't', 'g', 'g', 't', 't', 'a', 'a', 'g', 't', 'a', 't', 'g', 't', 'a', 't', 'a', 'a', 't', 'g', 'c', 'g', 'c', 'g', 'g', 'g', 'c', 't', 't', 'g', 't', 'c', 'g', 't', '+']

In [ ]:
# Convert the processed DNA sequences
# into a structured DataFrame.
# turn dataset into pandas DataFrame
dframe = pd.DataFrame(dataset)
print(dframe)

   0   1   2   3   4   5   6   7   8   9    ... 96  97  98  99  100 101 102  \
0    t   t   g   a   t   a   c   t   c   t  ...   c   c   t   a   g   c   g
1    a   g   t   a   c   g   a   t   g   t  ...   c   g   a   g   a   c   t
2    c   c   a   t   g   g   g   t   a   t  ...   g   c   t   a   g   t   a
3    t   t   c   t   a   g   g   c   c   t  ...   a   t   g   g   a   c   t
4    a   a   t   g   t   g   g   t   t   a  ...   g   a   a   g   g   a   t
5    g   t   a   t   a   c   g   a   t   a  ...   t   g   c   g   c   a   c
6    c   c   g   g   a   a   g   c   a   a  ...   a   g   c   t   a   t   t
7    a   c   a   a   t   a   t   a   a   t  ...   g   a   g   g   t   g   c
8    a   t   g   t   t   g   g   a   t   t  ...   a   c   a   t   g   g   a
9    t   g   a   g   a   g   g   a   a   t  ...   c   t   a   a   t   c   a
10   a   a   a   t   a   a   a   a   t   c  ...   c   t   c   c   c   c   c
11   c   c   c   g   c   g   g   c   a   c  ...   c   t   g   t   a   t   a
12   g   a   t   t   t   g   g   a   c   t  ...   t   c   a   c   g   c   a
13   c   g   a   a   a   a   a   c   t   c  ...   t   t   g   c   c   t   g
14   t   t   g   t   t   t   t   t   g   t  ...   a   t   t   a   c   a   a
15   t   t   t   c   t   g   t   t   c   t  ...   g   g   c   a   t   a   t
16   g   g   g   g   g   g   t   g   g   g  ...   a   t   a   g   c   a   t
17   c   t   c   a   a   a   a   a   a   t  ...   g   t   a   a   g   c   a
18   g   c   a   a   c   a   a   t   c   c  ...   a   g   t   a   a   g   a
19   t   a   t   g   g   a   g   a   a   a  ...   g   a   c   g   c   g   c
20   t   c   t   t   a   g   c   c   g   g  ...   c   t   a   a   a   g   c
21   c   g   a   g   a   a   c   t   g   g  ...   a   t   g   g   a   t   g
22   g   c   g   t   a   g   a   g   a   c  ...   t   t   a   g   c   c   a
23   g   t   c   g   a   g   t   t   c   c  ...   g   t   c   a   t   t   c
24   t   g   t   t   g   t   c   a   g   g  ...   t   c   c   a   t   t   a
25   g   a   t   t   c   t   t   t   t   g  ...   c   c   g   g   g   g   g
26   g   t   a   g   t   g   c   g   c   a  ...   a   a   c   a   c   a   a
27   t   t   t   c   g   c   c   a   c   a  ...   g   t   t   t   a   g   t
28   t   g   t   g   a   c   t   g   g   t  ...   c   g   t   g   t   g   t
29   a   g   t   g   a   g   g   c   t   a  ...   c   c   t   a   a   g   c
30   a   t   t   a   a   t   a   a   t   a  ...   t   g   g   g   a   g   a
31   g   g   t   g   a   a   t   t   c   c  ...   c   g   a   g   a   t   a
32   t   t   t   t   c   t   g   a   t   t  ...   g   t   c   c   t   t   t
33   a   c   t   a   c   a   a   c   g   c  ...   a   g   t   t   g   t   c
34   t   g   g   g   a   a   c   a   t   c  ...   c   t   c   a   c   t   t
35   g   t   t   a   c   a   g   g   g   c  ...   a   t   t   g   t   t   c
36   t   t   t   t   t   g   c   t   t   t  ...   a   t   g   a   t   t   g
37   a   a   a   g   a   a   a   a   a   a  ...   c   t   g   c   t   g   t
38   t   c   t   t   g   a   t   t   a   t  ...   t   g   t   g   c   c   g
39   a   a   c   t   a   a   a   a   a   a  ...   t   c   a   t   t   t   g
40   a   a   a   a   a   c   g   a   t   a  ...   g   g   t   c   t   g   a
41   t   t   t   g   t   t   t   t   c   t  ...   c   c   t   t   g   a   t
42   g   c   g   a   g   a   c   t   g   g  ...   a   a   a   c   t   a   g
43   c   t   c   a   c   g   a   g   c   c  ...   t   a   c   t   a   a   g
44   g   a   t   t   g   a   g   c   a   g  ...   a   t   t   g   g   g   a
45   c   a   a   a   c   g   c   t   a   c  ...   a   g   g   c   a   g   c
46   g   c   a   c   c   t   c   t   t   c  ...   a   t   t   a   c   a   g
47   g   g   c   t   t   c   c   c   g   a  ...   t   t   g   t   g   g   t
48   g   c   c   a   c   c   a   a   a   c  ...   g   a   a   g   t   g   t
49   c   a   a   a   c   g   t   a   a   c  ...   c   a   a   g   g   a   c
50   t   t   c   c   g   t   c   c   a   a  ...   t   t   c   a   c   a   a
51   t   c   c   a   t   t   a   a   t   c  ...   t   c   a   g   c   c   a
52   g   g   c   a   g   t   t   g   g   t  ...   t   g   t   t   c   t   c
53   t   c   g   a   g   a   g   a   g   g  ...   c   c   t   a   t   a   a
54   c   c   g   c   t   g   a   a   t   a  ...   t   t   a   t   a   t   t
55   g   a   c   t   a   g   a   c   t   c  ...   t   t   t   g   c   a   t
56   t   a   g   c   g   t   t   a   t   a  ...   g   t   t   a   g   t   g
57   +   +   +   +   +   +   +   +   +   +  ...   -   -   -   -   -   -   -

   103 104 105
0    c   c   t
1    g   t   a
2    c   c   a
3    g   g   c
4    a   t   a
5    c   c   t
6    t   c   t
7    a   t   a
8    c   c   a
9    g   a   t
10   a   a   a
11   t   t   a
12   g   g   a
13   a   g   t
14   g   c   a
15   a   c   a
16   t   t   g
17   g   c   g
18   c   t   a
19   c   a   g
20   t   a   g
21   g   a   c
22   a   c   t
23   g   g   c
24   t   g   t
25   g   g   a
26   c   t   a
27   t   c   t
28   t   t   g
29   c   t   g
30   c   g   c
31   g   a   a
32   t   g   c
33   t   g   t
34   a   g   c
35   c   g   a
36   t   t   t
37   g   t   t
38   g   t   a
39   a   t   g
40   t   t   c
41   t   t   c
42   g   g   a
43   t   c   a
44   c   t   t
45   a   g   c
46   c   a   a
47   c   a   a
48   a   a   t
49   a   g   c
50   g   g   a
51   g   a   a
52   c   g   g
53   t   g   a
54   t   a   a
55   c   a   c
56   c   c   t
57   -   -   -

[58 rows x 106 columns]

In [ ]:
# Transpose the DataFrame so that
# each row represents one DNA sample.
df = dframe.transpose()
print(df.iloc[:5])

  0  1  2  3  4  5  6  7  8  9   ... 48 49 50 51 52 53 54 55 56 57
0  t  a  c  t  a  g  c  a  a  t  ...  g  c  t  t  g  t  c  g  t  +
1  t  g  c  t  a  t  c  c  t  g  ...  c  a  t  c  g  c  c  a  a  +
2  g  t  a  c  t  a  g  a  g  a  ...  c  a  c  c  c  g  g  c  g  +
3  a  a  t  t  g  t  g  a  t  g  ...  a  a  c  a  a  a  c  t  c  +
4  t  c  g  a  t  a  a  t  t  a  ...  c  c  g  t  g  g  t  a  g  +

[5 rows x 58 columns]

In [ ]:
# for clarity, lets rename the last dataframe column to class
df.rename(columns = {57: 'Class'}, inplace = True)
print(df.iloc[:5])

   0  1  2  3  4  5  6  7  8  9  ... 48 49 50 51 52 53 54 55 56 Class
0  t  a  c  t  a  g  c  a  a  t  ...  g  c  t  t  g  t  c  g  t     +
1  t  g  c  t  a  t  c  c  t  g  ...  c  a  t  c  g  c  c  a  a     +
2  g  t  a  c  t  a  g  a  g  a  ...  c  a  c  c  c  g  g  c  g     +
3  a  a  t  t  g  t  g  a  t  g  ...  a  a  c  a  a  a  c  t  c     +
4  t  c  g  a  t  a  a  t  t  a  ...  c  c  g  t  g  g  t  a  g     +

[5 rows x 58 columns]

In [ ]:
# Display the first five rows of the dataset
df.head()

   0  1  2  3  4  5  6  7  8  9  ... 48 49 50 51 52 53 54 55 56 Class
0  t  a  c  t  a  g  c  a  a  t  ...  g  c  t  t  g  t  c  g  t     +
1  t  g  c  t  a  t  c  c  t  g  ...  c  a  t  c  g  c  c  a  a     +
2  g  t  a  c  t  a  g  a  g  a  ...  c  a  c  c  c  g  g  c  g     +
3  a  a  t  t  g  t  g  a  t  g  ...  a  a  c  a  a  a  c  t  c     +
4  t  c  g  a  t  a  a  t  t  a  ...  c  c  g  t  g  g  t  a  g     +

[5 rows x 58 columns]

In [ ]:
# The describe() function does not provide useful
# information for categorical DNA sequence data.
series = []
for name in df.columns:
    series.append(df[name].value_counts())

info = pd.DataFrame(series)
details = info.transpose()
print(details)

   count  count  count  count  count  count  count  count  count  count  ...  \
t   38.0   26.0   27.0   26.0   22.0   24.0   30.0   32.0   32.0   28.0  ...
c   27.0   22.0   21.0   30.0   19.0   18.0   21.0   20.0   22.0   22.0  ...
a   26.0   34.0   30.0   22.0   36.0   42.0   38.0   34.0   33.0   36.0  ...
g   15.0   24.0   28.0   28.0   29.0   22.0   17.0   20.0   19.0   20.0  ...
+    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  ...
-    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  ...

   count  count  count  count  count  count  count  count  count  count
t   21.0   22.0   23.0   33.0   35.0   30.0   23.0   29.0   34.0    NaN
c   36.0   42.0   31.0   32.0   21.0   32.0   29.0   29.0   17.0    NaN
a   23.0   24.0   28.0   27.0   25.0   22.0   26.0   24.0   27.0    NaN
g   26.0   18.0   24.0   14.0   25.0   22.0   28.0   24.0   28.0    NaN
+    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   53.0
-    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   53.0

[6 rows x 58 columns]

In [ ]:
# Unfortunately, we can't run machine learning algorithms on the data in 'String' formats. As a result, we need to switch
# it to numerical data. This can easily be accomplished using the pd.get_dummies() function
numerical_df = pd.get_dummies(df)
numerical_df.iloc[:5]

,0_a,0_c,0_g,0_t,1_a,1_c,1_g,1_t,2_a,2_c,...,55_a,55_c,55_g,55_t,56_a,56_c,56_g,56_t,Class_+,Class_-
0,False,False,False,True,True,False,False,False,False,True,...,False,False,True,False,False,False,False,True,True,False
1,False,False,False,True,False,False,True,False,False,True,...,True,False,False,False,True,False,False,False,True,False
2,False,False,True,False,False,False,False,True,True,False,...,False,True,False,False,False,False,True,False,True,False
3,True,False,False,False,True,False,False,False,False,False,...,False,False,False,True,False,True,False,False,True,False
4,False,False,False,True,False,True,False,False,False,False,...,True,False,False,False,False,False,True,False,True,False

In [ ]:
# Verify that the dataset does not contain
# any missing values before model training.
df.isnull().sum()

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       0
25       0
26       0
27       0
28       0
29       0
30       0
31       0
32       0
33       0
34       0
35       0
36       0
37       0
38       0
39       0
40       0
41       0
42       0
43       0
44       0
45       0
46       0
47       0
48       0
49       0
50       0
51       0
52       0
53       0
54       0
55       0
56       0
Class    0
dtype: int64

In [ ]:
# We don't need both class columns.  Lets drop one then rename the other to simply 'Class'.
df = numerical_df.drop(columns=['Class_-'])

df.rename(columns = {'Class_+': 'Class'}, inplace = True)
print(df.iloc[:5])

     0_a    0_c    0_g    0_t    1_a    1_c    1_g    1_t    2_a    2_c  ...  \
0  False  False  False   True   True  False  False  False  False   True  ...
1  False  False  False   True  False  False   True  False  False   True  ...
2  False  False   True  False  False  False  False   True   True  False  ...
3   True  False  False  False   True  False  False  False  False  False  ...
4  False  False  False   True  False   True  False  False  False  False  ...

    54_t   55_a   55_c   55_g   55_t   56_a   56_c   56_g   56_t  Class
0  False  False  False   True  False  False  False  False   True   True
1  False   True  False  False  False   True  False  False  False   True
2  False  False   True  False  False  False  False   True  False   True
3  False  False  False  False   True  False   True  False  False   True
4   True   True  False  False  False  False  False   True  False   True

[5 rows x 229 columns]

In [ ]:

# Split the dataset into training and testing sets
# to evaluate model performance on unseen data.
from sklearn import model_selection

# Create X and Y datasets for training
X = np.array(df.drop(['Class'], axis=1))
y = np.array(df['Class'])

# define seed for reproducibility
seed = 1

# split data into training and testing datasets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, random_state=seed)

## Step 3: Training and Testing the Classification Algorithms

Now that we have preprocessed the data and built our training and testing datasets, we can start to deploy different classification algorithms. It's relatively easy to test multiple models; as a result, we will compare and contrast the performance of ten different algorithms.

In [ ]:
# =====================================================
# Model Training
# Train multiple machine learning classifiers
# and compare their performance.
# =====================================================
# Now that we have our dataset, we can start building algorithms! We'll need to import each algorithm we plan on using
# from sklearn.  We also need to import some performance metrics, such as accuracy_score and classification_report.

from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# define scoring method
scoring = 'accuracy'

# Define models to train
names = ["Nearest Neighbors", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "SVM Linear", "SVM RBF", "SVM Sigmoid"]

classifiers = [
    KNeighborsClassifier(n_neighbors = 3),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    SVC(kernel = 'linear'),
    SVC(kernel = 'rbf'),
    SVC(kernel = 'sigmoid')
]

models = zip(names, classifiers)

# evaluate each model in turn
results = []
names = []

for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state = seed, shuffle=True)
    cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)

Nearest Neighbors: 0.796429 (0.102332)

/usr/local/lib/python3.12/dist-packages/sklearn/gaussian_process/kernels.py:442: ConvergenceWarning: The optimal value found for dimension 0 of parameter k1__constant_value is close to the specified lower bound 1e-05. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(

Gaussian Process: 0.855357 (0.160605)
Decision Tree: 0.669643 (0.152624)
Random Forest: 0.607143 (0.118451)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

Neural Net: 0.912500 (0.097628)
AdaBoost: 0.873214 (0.111932)
Naive Bayes: 0.837500 (0.112500)
SVM Linear: 0.912500 (0.097628)
SVM RBF: 0.875000 (0.111803)
SVM Sigmoid: 0.925000 (0.100000)

In [ ]:
# Remember, performance on the training data is not that important. We want to know how well our algorithms
# can generalize to new data.  To test this, let's make predictions on the validation dataset.

for name, model in models:
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(name)
    print(accuracy_score(y_test, predictions))
    print(classification_report(y_test, predictions))


# Accuracy - ratio of correctly predicted observation to the total observations.
# Precision - (false positives) ratio of correctly predicted positive observations to the total predicted positive observations
# Recall (Sensitivity) - (false negatives) ratio of correctly predicted positive observations to the all observations in actual class - yes.
# F1 score - F1 Score is the weighted average of Precision and Recall. Therefore, this score takes both false positives and false

# Conclusion

This project successfully demonstrates an end-to-end machine learning workflow for DNA sequence classification.

The project includes:

- Data preprocessing
- Feature engineering
- Model training
- Performance evaluation
- Model comparison

This work was completed as part of the **Data Science Bootcamp Internship at IIIT Kottayam**, providing practical experience in applying machine learning techniques to bioinformatics data.